development:
  password: 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
  theme_id: "126680006810"
  store: rotimaticus.myshopify.com
production:
  password: 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
  theme_id: "126668734618"
  store: rotimaticus.myshopify.com
