development:
  password: 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
  #dev theme
  # theme_id: "120726716570"
  # live + dev merge theme
  # theme_id: "121036963994"
  # V 1.1 DEV
  theme_id: "121119375514"
  store: rotimaticus.myshopify.com
production:
  password: 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
  theme_id: "121119375514"
  store: rotimaticus.myshopify.com
