development:
  password: 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
  theme_id: "126877892762"
  store: rotimaticus.myshopify.com
production:
  password: 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
  theme_id: "126807900314"
  store: rotimaticus.myshopify.com
